mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mysite import settings
from shop.views import ProductDetailView, ProductListView, ProductUpdateView, ProductCreateView, ProductDeleteView, \
      CategoryListView, PromotionCreateView, custom_page_not_found_view
from users.views import signup

urlpatterns = [
      path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
      path('product/', ProductListView.as_view(), name='product_list'),
      path('admin/', admin.site.urls),
      path('users/', include('users.urls', namespace='users')),
      path('users/accounts/signup', signup, name='sign_up'),
      path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_edit'),
      path('product/create/', ProductCreateView.as_view(), name='product_create'),
      path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
      path('', CategoryListView.as_view(), name='category_list'),
      path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
      path('promotion/create/', PromotionCreateView.as_view(), name='promotion_create'),
      path('404/', custom_page_not_found_view)


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL)

mysite/users/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include

from mysite import settings
from users.views import signup, UserDetailView, UserUpdateView, ConversationListView, ConversationDetailView, \
    ConversationCreateView, MessageCreateView, deleteuser, ProductBYUserListView, Activate

app_name = 'users'

urlpatterns = [
    url(r'^signup/$', signup, name='signup'),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    path("profile/<int:pk>/", UserDetailView.as_view(), name='user_detail'),
    path("profile/update/<int:pk>/", UserUpdateView.as_view(), name='user_update'),
    path("conversations/", ConversationListView.as_view(), name='conversations'),
    path("conversations/<int:pk>/", ConversationDetailView.as_view(), name='conversation_detail'),
    path("conversations/create/", ConversationCreateView.as_view(), name='conversation_create'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('delete_account/<int:pk>/', deleteuser, name='delete_user'),
    path('my_porduct/', ProductBYUserListView.as_view(), name='my_product'),
    path('activate/<str:uuid>/<str:token>', Activate.as_view(), name='activate'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/shop/models.py
from decimal import Decimal

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from hitcount.models import HitCount
from django import forms


class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(decimal_places=2, max_digits=8, max_length=8)
    description = models.TextField(max_length=5000)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    image = models.FileField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


PROMOTION_CHOICES = (
    (1, 'highlight'),
    (2, 'bold')
)


class Promotion(models.Model):
    promotion_type = models.SmallIntegerField(choices=PROMOTION_CHOICES, verbose_name='Typ promocji')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Produkt')
    end_date = models.DateTimeField(verbose_name='Data zakończenia')

    def get_price(self):
        if self.promotion_type == PROMOTION_CHOICES[0][0]:
            return Decimal('5')
        elif self.promotion_type == PROMOTION_CHOICES[1][0]:
            return Decimal('8')
        return Decimal('10')










# ToDo Sortowanie od najnowszego albo od najstarszego

mysite/shop/forms.py
import datetime
from urllib import request

from django.contrib.admin import widgets
from django.core.exceptions import ValidationError
from django.forms import ModelForm, DateTimeField

from shop import models
from shop.models import Promotion, Product
from django import forms
from django.utils.translation import ugettext_lazy as _


class PromotionCreateForm(ModelForm):
    class Meta:
        model = Promotion
        fields = '__all__'
        widgets = {
            'end_date': forms.DateInput(format='%m/%d/%Y',
                                        attrs={'class': 'form-control', 'placeholder': 'Wybierz date', 'type': 'date'})}

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(PromotionCreateForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['product'].queryset = Product.objects.filter(user=user)

mysite/shop/views.py
import random
from urllib import request

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, InvalidPage, Paginator
from django.db.models import F, Q, Count
from django.shortcuts import redirect, render
from django.template import response, RequestContext
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView, FormView
from hitcount.views import HitCountDetailView

from shop.forms import PromotionCreateForm
from shop.models import Product, Category, Promotion, PROMOTION_CHOICES
from users.models import UserInfo


class ProductDetailView(HitCountDetailView):
    model = Product
    count_hit = True


class ProductListView(ListView):
    model = Product
    paginate_by = 16

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        products = []
        for product in context['object_list']:
            promotions = list(
                product.promotion_set
                    .filter(end_date__gte=timezone.now())
                    .values_list('promotion_type', flat=True)
                    .distinct()
            )

            product.promotions = [dict(PROMOTION_CHOICES).get(promotion) for promotion in promotions]
            products.append(product)
        context['object_list'] = products
        context['categories'] = Category.objects.all()
        return context

    def get_queryset(self):
        products = Product.objects.all().annotate(highlight=Count('promotion',
                                                                  filter=Q(promotion__end_date__gte=timezone.now(),
                                                                           promotion__promotion_type=
                                                                           PROMOTION_CHOICES[0][0]))).order_by(
            '-highlight')
        # products = products.order_by('-promotion__promotion_type')
        category = self.request.GET.get('category')

        if category:
            products = products.filter(category_id=category)
        product_name = self.request.GET.get('q')
        if product_name:
            products = products.filter(name__icontains=product_name)
        return products


# TODO filtorwanie ogłoszen poprzez najwieksza ilosc wyśiwtleń

class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'price', 'description', 'category', 'image']

    def get_queryset(self):
        return Product.objects.filter(user=self.request.user)

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super(ProductUpdateView, self).form_valid(form)


class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'price', 'description', 'category', 'image']
    template_name_suffix = '_create_form'

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super(ProductCreateView, self).form_valid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('product_list')

    def get_queryset(self):
        return Product.objects.filter(user=self.request.user)


class CategoryListView(ListView):
    model = Category


class PromotionCreateView(FormView):
    form_class = PromotionCreateForm
    template_name = 'shop/promotion_form.html'

    def form_valid(self, form):
        # Todo filtorwanie produktów użtykownika
        # ToDo przekierowanie na formularz
        if form.is_valid():
            promotion = form.save(commit=False)
            user_info, created = UserInfo.objects.get_or_create(user=self.request.user)
            price = promotion.get_price()
            if user_info.balance > price:
                user_info.balance = F('balance') - price
                user_info.save()
                promotion.save()
            else:
                messages.error(self.request, 'Nie masz tyle pieniędzy. Doładuj Konto ! ')
                return redirect('promotion_create')
            return redirect('product_list')
        return redirect('product_list')

    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form_kwargs = self.get_form_kwargs()
        form_kwargs['user'] = request.user
        form = form_class(**form_kwargs)
        context = self.get_context_data(**kwargs)
        context['form'] = form

        return self.render_to_response(context)


def custom_page_not_found_view(request):
    return render(request, 'templates/404.html', status=404)

mysite/shop/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}FreeSale{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% load static %}
<!--    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style48.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link rel="icon"
      type="image/png"
      href="{% static 'image/idea.png' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">

    <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
    <a href="https://www.vecteezy.com/free-vector/people"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse ml-5" id="navbarNav">

        <a class="freesale2 navbar-brand mt-2" href="{% url 'category_list' %}">FreeSale</a>
    <ul class="navbar-nav ml-auto">

      <li class="nav-item">
        <a class="nav-link" href="/product">Produkty</a>
      </li>
        {% if user.is_authenticated %}
         <li class="nav-item">
            <a href="{% url 'product_create'%}" class="nav-link">Dodaj Ogłoszenie</a>
        </li>
            <li class="nav-item">
            <p class="nav-link">{{ user.user_info.balance}}</p>
        </li>
        <li class="nav-item">
        <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Profil</a>
             <div class="dropdown-menu p-3 profil" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="/users/profile/update/{{ request.user.pk }}">Twój Profil</a>
                 <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'users:conversations'%}">Wiadmości</a>
                 <div class="dropdown-divider"></div>
                 <a class="dropdown-item" href="{% url 'users:my_product'%}">Twoje Ogłoszenia</a>
             </div>

    </div>
        </li>


        <li class="logout nav-item pr-3 rounded">
            <a class="logout nav-link text-center" href="/users/accounts/logout">Wyloguj</a>
      </li>

        {% else %}
      <li class="nav-item">
        <a class="nav-link" href="/users/accounts/login">Logowanie</a>
      </li>
<!--      <li class="nav-item">-->
<!--        <a class="nav-link " href="/users/accounts/signup">Rejestracja</a>-->
<!--      </li>-->
        {% endif %}
    </ul>
  </div>
  </div>
</nav>

{% csrf_token %}
 {% for message in messages %}
  <div class="alert col-6 offset-3 text-center {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
<div class="container">

        </div>
    <div class="content container">
        <div class="row">
            <div class="col-12">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>

</div>
{%  block footer %}
<footer class="stopka bg-primary h-25 d-inline-block w-100 p-3">
<div class="col-3 offset-5 d-inline-flex">

    <img src="{% static 'image/copyright.png' %}" class="stopka-image mt-3"><p class="text-light ml-4 mt-3">Paweł Rutkowski</p>
    <div class="col-2 text-center">
        <a href="https://www.linkedin.com/in/pawe%C5%82-rutkowski-8a121b202/" ><i class="text-white linkedin rounded ikonka fab fa-linkedin-in"/></i></a>
    </div>
    <div class="col-2">
        <a class="text-dark" href="https://github.com/Pawelooo"><i class="ikonka fab fa-github"></i></a>
    </div>
</div>
</footer>
{% endblock %}
<!-- JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script>
// When the user scrolls the page, execute myFunction
window.onscroll = function() {myFunction()};

function myFunction() {
  var winScroll = document.body.scrollTop || document.documentElement.scrollTop;
  var height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
  var scrolled = (winScroll / height) * 100;
  document.getElementById("myBar").style.width = scrolled + "%";
}
</script>
</body>
</html>