mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mysite import settings
from shop.views import ProductDetailView, ProductListView, ProductUpdateView, ProductCreateView, ProductDeleteView, \
      CategoryListView, PromotionCreateView, custom_page_not_found_view
from users.views import signup

urlpatterns = [
      path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
      path('product/', ProductListView.as_view(), name='product_list'),
      path('admin/', admin.site.urls),
      path('users/', include('users.urls', namespace='users')),
      path('users/accounts/signup', signup, name='sign_up'),
      path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_edit'),
      path('product/create/', ProductCreateView.as_view(), name='product_create'),
      path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
      path('', CategoryListView.as_view(), name='category_list'),
      path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
      path('promotion/create/', PromotionCreateView.as_view(), name='promotion_create'),
      path('404/', custom_page_not_found_view)


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL)

mysite/users/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include

from mysite import settings
from users.views import signup, UserDetailView, UserUpdateView, ConversationListView, ConversationDetailView, \
    ConversationCreateView, MessageCreateView, deleteuser, ProductBYUserListView, Activate

app_name = 'users'

urlpatterns = [
    url(r'^signup/$', signup, name='signup'),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    path("profile/<int:pk>/", UserDetailView.as_view(), name='user_detail'),
    path("profile/update/<int:pk>/", UserUpdateView.as_view(), name='user_update'),
    path("conversations/", ConversationListView.as_view(), name='conversations'),
    path("conversations/<int:pk>/", ConversationDetailView.as_view(), name='conversation_detail'),
    path("conversations/create/", ConversationCreateView.as_view(), name='conversation_create'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('delete_account/<int:pk>/', deleteuser, name='delete_user'),
    path('my_porduct/', ProductBYUserListView.as_view(), name='my_product'),
    path('activate/<str:uuid>/<str:token>', Activate.as_view(), name='activate'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/shop/models.py
from decimal import Decimal

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from hitcount.models import HitCount
from django import forms


class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(decimal_places=2, max_digits=8, max_length=8)
    description = models.TextField(max_length=5000)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    image = models.FileField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


PROMOTION_CHOICES = (
    (1, 'highlight'),
    (2, 'bold')
)


class Promotion(models.Model):
    promotion_type = models.SmallIntegerField(choices=PROMOTION_CHOICES, verbose_name='Typ promocji')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Produkt')
    end_date = models.DateTimeField(verbose_name='Data zakończenia')

    def get_price(self):
        if self.promotion_type == PROMOTION_CHOICES[0][0]:
            return Decimal('5')
        elif self.promotion_type == PROMOTION_CHOICES[1][0]:
            return Decimal('8')
        return Decimal('10')










# ToDo Sortowanie od najnowszego albo od najstarszego

mysite/shop/forms.py
import datetime
from urllib import request

from django.contrib.admin import widgets
from django.core.exceptions import ValidationError
from django.forms import ModelForm, DateTimeField

from shop import models
from shop.models import Promotion, Product
from django import forms
from django.utils.translation import ugettext_lazy as _


class PromotionCreateForm(ModelForm):
    class Meta:
        model = Promotion
        fields = '__all__'
        widgets = {
            'end_date': forms.DateInput(format='%m/%d/%Y',
                                        attrs={'class': 'form-control', 'placeholder': 'Wybierz date', 'type': 'date'})}

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(PromotionCreateForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['product'].queryset = Product.objects.filter(user=user)

mysite/shop/views.py
import random
from urllib import request

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, InvalidPage, Paginator
from django.db.models import F, Q, Count
from django.shortcuts import redirect, render
from django.template import response, RequestContext
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView, FormView
from hitcount.views import HitCountDetailView

from shop.forms import PromotionCreateForm
from shop.models import Product, Category, Promotion, PROMOTION_CHOICES
from users.models import UserInfo


class ProductDetailView(HitCountDetailView):
    model = Product
    count_hit = True


class ProductListView(ListView):
    model = Product
    paginate_by = 16

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        products = []
        for product in context['object_list']:
            promotions = list(
                product.promotion_set
                    .filter(end_date__gte=timezone.now())
                    .values_list('promotion_type', flat=True)
                    .distinct()
            )

            product.promotions = [dict(PROMOTION_CHOICES).get(promotion) for promotion in promotions]
            products.append(product)
        context['object_list'] = products
        context['categories'] = Category.objects.all()
        return context

    def get_queryset(self):
        products = Product.objects.all().annotate(highlight=Count('promotion',
                                                                  filter=Q(promotion__end_date__gte=timezone.now(),
                                                                           promotion__promotion_type=
                                                                           PROMOTION_CHOICES[0][0]))).order_by(
            '-highlight')
        # products = products.order_by('-promotion__promotion_type')
        category = self.request.GET.get('category')

        if category:
            products = products.filter(category_id=category)
        product_name = self.request.GET.get('q')
        if product_name:
            products = products.filter(name__icontains=product_name)
        return products


# TODO filtorwanie ogłoszen poprzez najwieksza ilosc wyśiwtleń

class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'price', 'description', 'category', 'image']

    def get_queryset(self):
        return Product.objects.filter(user=self.request.user)

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super(ProductUpdateView, self).form_valid(form)


class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'price', 'description', 'category', 'image']
    template_name_suffix = '_create_form'

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super(ProductCreateView, self).form_valid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('product_list')

    def get_queryset(self):
        return Product.objects.filter(user=self.request.user)


class CategoryListView(ListView):
    model = Category


class PromotionCreateView(FormView):
    form_class = PromotionCreateForm
    template_name = 'shop/promotion_form.html'

    def form_valid(self, form):
        # Todo filtorwanie produktów użtykownika
        # ToDo przekierowanie na formularz
        if form.is_valid():
            promotion = form.save(commit=False)
            user_info, created = UserInfo.objects.get_or_create(user=self.request.user)
            price = promotion.get_price()
            if user_info.balance > price:
                user_info.balance = F('balance') - price
                user_info.save()
                promotion.save()
            else:
                messages.error(self.request, 'Nie masz tyle pieniędzy. Doładuj Konto ! ')
                return redirect('promotion_create')
            return redirect('product_list')
        return redirect('product_list')

    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form_kwargs = self.get_form_kwargs()
        form_kwargs['user'] = request.user
        form = form_class(**form_kwargs)
        context = self.get_context_data(**kwargs)
        context['form'] = form

        return self.render_to_response(context)


def custom_page_not_found_view(request):
    return render(request, 'templates/404.html', status=404)

mysite/shop/templates/shop/category_list.html
{% extends 'base.html' %}
{% block content%}


<div class="mt-5 row mb-5">
 {% for category in object_list %}
  <div class=" col-lg-3 col-md-4 col-12 mt-3 mb-3 text-center" >
      <a href="{% url 'product_list'%}?category={{ category.id }}">
          <div class="card-category ">

            {% load static %}
            {% if category.image %}
                <a href="{% url 'product_list'%}?category={{ category.id }}">
                <img src="{{category.image.url}} " class="obrazek card-img-top rounded-circle">

            {% else %}

                <img  src="../../static/image/image.jpg" class="card-img-top rounded-circle">

                {% endif %}
              <p class="nazwa_kategori text-center mt-4 font-weight-bold">{{ category.name }}</p>
          </div>
      </a>
  </div>
{% endfor %}
</div>


{% endblock %}

mysite/shop/templates/shop/product_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<form method="post">{% csrf_token %}
    <div class="alert alert-danger" role="alert">
    <h5 class="mt-0 text-center">Czy na pewno chcesz usunąć swoje ogłoszenie "{{ object }}"?</h5>
    </div>
    <div class="offset-4 col-4 text-center">
        <button type="submit" class="btn btn-danger mb-2">Potwierdź</button>
        <a href="{% url 'product_detail' object.pk%}" class="btn btn-outline-secondary mb-2">Anuluj</a>
    </div>
</form>
{% endblock %}

mysite/shop/templates/shop/product_create_form.html
{% extends 'base.html' %}
{% block content%}

    <div class="form-group card-shadow col-12 mt-3">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="col-10 offset-1">
          <h3 class="pt-5 mb-5 text-center">Dodawanie nowego produktu</h3>
         <div class="fieldWrapper col-12 mb-3 text-center p-3">
            {{ form.name.errors }}
            <div class="label">
                <label for="{{ form.name.id_for_label }}">Nazwa produktu</label>
            </div>
                {{ form.name }}
        </div>
        <div class="fieldWrapper col-12 mb-3 text-center">
            {{ form.price.errors }}
            <div class="price">
                <label for="{{ form.price.id_for_label }}">Cena</label>
            </div>
                {{ form.price }}
        </div>
         <div class="fieldWrapper col-12 mb-3 text-center">
            {{ form.description.errors }}
            <div class="description">
                <label for="{{ form.description.id_for_label }}">Opis</label>
            </div>
            {{ form.description }}
        </div>
        <div class="fieldWrapper col-12 mb-3 text-center">
            {{ form.category.errors }}
            <div class="category">
                <label for="{{ form.category.id_for_label }}">Kategoria</label>
            </div>
            {{ form.category }}
        </div>
        <div class="fieldWrapper col-12 mb-3 text-center">
            {{ form.image.errors }}
            <div class="picture">
                Obraz
                <div class="text-center">
                    <input required name="image" type="file" multiple class="form-control-file">
                </div>
            </div>

        </div>
        <div class="fieldWrapper offset-lg-3 col-lg-6 col-12 mt-5 pb-5 text-center">

                <button type="submit" class="button btn btn-outline-dark">Dodaj produkt</button>

        </div>
          
      </div>
        </form>
    <a href="/product/"  class="button btn btn-outline-secondary" >Anuluj</a>
    </div>


{% endblock %}

mysite/shop/templates/shop/product_detail.html
{% extends 'base.html' %}

{%  load hitcount_tags %}

{% block content%}

<div class="p-5 row offer-single card-shadow mt-3">
    <div class="col-12 mb-5">
      <div class="col-2 count mt-3 mb-5">
            <p>Wyświetlenia: {%  get_hit_count for product %} <i class="fa fa-eye" aria-hidden="true"></i></p>
    </div>

        {% if object.image %}
                <img src="{{object.image.url}} " class="card-img-top ">
              {% else %}
                <img  src="../../../media/no-image-icon.png" class="card-img-top ">
              {% endif %}
    </div>

    <div class="col-6 mb-5">
        <h3>{{ object.name }}</h3>
    </div>
    <div class="col-6 mt-5 text-right">
        <h3>{{ object.price }} zł</h3>
    </div>
    <div class="col-12 text-justify mb-5 mt-5">
        <p>{{ object.description }}</p>
    </div>
      <div class="col-6 text-left ">
          <p class="pb-0 mb-0 bold">Kategoria</p>
        <p class="font-weight-bold"><a href="/product/?category={{object.category.id}}"><bold>{{ object.category }}</bold></a></p>
    </div>
    <div class="user mt-5 col-6 text-right ">
                <a href = "/users/profile/{{ object.user.pk }}" class="font-weight-bold ">{{ object.user }} </a>


    </div>
</div>

<div class="offer-single-contact card-shadow row mb-5">
    <div class="row container">
        <div class="col-6 text-left left">
            {% if object.user.user_info.phone %}
                <i class="fas fa-phone-alt"></i> {{ object.user.user_info.phone }}
            {% else %}
                <i class="fas fa-phone-slash"></i> Brak numeru
            {% endif %}
        </div>
        <div class="offset-3"></div>
        <div class="col-3 text-right">
           <a href="{%  url 'users:conversation_create'  %}?user_to={{ object.user_id }}"> <button type="button" href="" class="btn btn-block btn-primary" data-bs-toggle="modal" >
              Wyślij Wiadomość
            </button>
           </a>
        </div>
    </div>
</div>

{% if object.user == request.user %}
    <div class="row mt-5 mb-5">
        <div class="offset-3"></div>
        <div class="col-3 text-center">
            <a href="{% url 'product_edit' object.pk%}" class="btn btn-block btn-lg btn-outline-success">Edytuj</a>

        </div>
         <div class="col-3 text-center">
            <a href="{% url 'product_delete' object.pk%}" class="btn btn-block btn-lg btn-outline-danger">Usuń</a>
        </div>
    </div>
{% endif %}

{% endblock %}

mysite/shop/templates/shop/product_form.html
{% extends 'base.html' %}
{% block content%}
<div class="p-5 mb-5 row card-shadow">
    <div class="col-12 mb-5">
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.non_field_errors }}
            <div class=" text-center mb-5"><h3>Aktualizowanie ogłoszenia</h3></div>
            <div class="fieldWrapper col-12 mb-4 text-center">
                {{ form.name.errors }}
                <div class="label">
                    <label for="{{ form.name.id_for_label }}"><h5>Nazwa produktu</h5></label>
                </div>
                {{ form.name }}
            </div>
            <div class="fieldWrapper col-12 mb-4 text-center">
                {{ form.price.errors }}
                <div class="price">
                    <label for="{{ form.price.id_for_label }}"><h5>Cena</h5></label>
                </div>
                {{ form.price }}
            </div>
             <div class="fieldWrapper col-12 mb-4 text-center">
                {{ form.description.errors }}
                <div class="description">
                    <label for="{{ form.description.id_for_label }}"><h5>Opis</h5></label>

                </div>
                {{ form.description }}
            </div>
            <div class="fieldWrapper col-12 mb-4 text-center">
                {{ form.category.errors }}
                <div class="category">

                    <label for="{{ form.category.id_for_label }}"><h5>Kategoria</h5></label>
                </div>
                {{ form.category }}
            </div>
            <div class="fieldWrapper col-12 mb-4 text-center">
                {{ form.image.errors }}
                <div class="picture">
                    <label for="{{ form.image.id_for_label }}"><h5>Obraz</h5></label>
                </div>
                {{ form.image }}
            </div>
            <div class="fieldWrapper offset-lg-3 col-lg-6 col-12 mt-5 text-center">
                <button type="submit" class="button btn btn-outline-dark" >Zaaktualizuj</button>

            </div>


        </form>


    </div>
</div>
     <a href="{% url 'product_detail' object.pk%}" class="button btn btn-secondary">Anuluj</a>
{% endblock %}

mysite/shop/templates/shop/product_list.html
{% extends 'base.html' %}
{% block content%}

    <form method="get" action="/product/" class="row">
      <div class="col-6">
        <input type="text" class="form-control" name="q" id="id_q" value="{{ query }}" placeholder="Wyszukaj"/>
      </div>
      <div class="col-3">

        <select name="category" class="custom-select">
          <option value="">Wszystkie produkty</option>
          {% for category in categories %}
              <option value="{{category.id}}" {{category.name}} {% if category.id == category_id %} selected{% endif %} >{{category.name}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="col-3 ">
          <button type="submit" class="btn btn-outline-warning btn-block border-warning rounded ">Znajdź</button>
      </div>

    </form>

<div class="mt-5 mb-5 row">

 {% for product in object_list %}
     <div class="col-3 mt-3 mb-3" >
         <a href="{{product.id}}">
         <div class="offert-list card border " >

               {% if product.image %}
                    <img src="{{product.image.url}}" class="ogłoszenie card-img-top ">
               {% else %}
                    <img  src="../../../media/no-image-icon.png" class="card-img-top ">
             {% endif %}
          <div class="card-body text-center">
          {% if 'bold' in product.promotions %}
              <bold>
                <h5 class="card-title ">{{ product.name|slice:"0:30" }}{% if product.name|length > 30 %}...{% endif %}</h5>
                <p class="card-text mt-2">{{ product.description|slice:"0:50" }}{% if product.description|length > 50 %}...{% endif %}</p>
                <p class="zobacz col-12 text-center">Zobacz</p>
              </bold>
          {% else %}
              <h5 class="card-title">{{ product.name|slice:"0:30" }}{% if product.name|length > 30 %}...{% endif %}</h5>
                <p class="card-text mt-2">{{ product.description|slice:"0:50" }}{% if product.description|length > 50 %}...{% endif %}</p>
                <p class="zobacz col-12 text-center">Zobacz ELO</p>
          {% endif %}
          </div>
        </div>
          </a>
      </div>
{% endfor %}
</div>
    <div class="znaki col-2 offset-5">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
            {% else %}
                <li class="disabled mr-2 mt-1"><span><i class="fa fa-chevron-left" aria-hidden="true"></i></span></li>
            {% endif %}
            {% if page_obj.number|add:'-4' > 1 %}
                <li><a class="mr-2 ml-3" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active btn-outline-info p-2  "><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                    <li><a class="button btn-outline-info mr-1 ml-1 p-1" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                <li><a class="mr-3 ml-2" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
            {% endif %}

            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class=""><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
            {% else %}
                <li class="disabled ml-2 mt-1"><span><i class="fa fa-chevron-right" aria-hidden="true"></i></span></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

mysite/shop/templates/shop/promotion_form.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
     <div class="card-shadow p-5 col-8 offset-2 mb-5">
         <div class="col-10 offset-1 mb-3 text-center pb-2">
              <h2>Promuj swoje ogłoszenie</h2>
          </div>
        {{ form.as_p }}




        <div class="fieldWrapper offset-lg-3 col-lg-6 col-12 mt-5 pb-5 text-center">
            <button type="submit" class="button btn btn-outline-dark">Promuj </button>
        </div>
     </div>
</form>


{% endblock %}